create database ESTAGIARIO_RENNER 


CREATE TABLE USUARIO(
COD_USO INT NOT NULL IDENTITY(1,1),
NOME VARCHAR(100),
ATIVO BIT,
CONSTRAINT PK_USUARIO PRIMARY KEY(COD_USO)
)


INSERT INTO USUARIO(
NOME, ATIVO 
)
VALUES('RAFAEL', 0)


SELECT COUNT(COD_USO) AS KTD ,ATIVO
FROM USUARIO 
GROUP BY ATIVO
HAVING COUNT(COD_USO) > 1

SELECT TOP 3*
FROM USUARIO 


SELECT TOP 3 COD_USO AS "CODIGO USUARIO" 
FROM USUARIO

SELECT NOME AS "LISTA DE NOMES"
FROM USUARIO 

CREATE TABLE PRODUTOS(
PRO_USO INT NOT NULL IDENTITY(1,1),
NOME VARCHAR(100),
ATIVO BIT,
CONSTRAINT PK_PODUTOS PRIMARY KEY(PRO_USO))

INSERT INTO PRODUTOS(
NOME, ATIVO 
)
VALUES('GELADEIRA', 1000)

SELECT * FROM PRODUTOS

CREATE TABLE ENDERECO(
PRO_USO INT NOT NULL IDENTITY(1,1),
RUA VARCHAR(100),
BAIRRO VARCHAR(100),
ATIVO BIT,
CONSTRAINT PK_ENDERECO PRIMARY KEY(PRO_USO))

SELECT * FROM ENDERECO


INSERT INTO ENDERECO(
RUA,BAIRRO, ATIVO 
)
VALUES('RUA SIGA','SERGIO ANTONIO CORONA 1', 2) 
SELECT RUA AS "LISTA DE RUAS"
FROM ENDERECO  