CREATE TABLE CANAL (
CANALID INT PRIMARY KEY,
NOME VARCHAR(150) NOT NULL,
CONTAGEMINSCRITOS INT DEFAULT 0,
DATACRIAÇAO DATETIME NOT NULL
);

SELECT * FROM CANAL

CREATE TABLE VIDEO (
VIDEOID INT PRIMARY KEY,
NOME VARCHAR (150) NOT NULL,
VIZUALIZACOES INT DEFAULT 0,
LIKES INT DEFAULT 0,
DURACAO INT NOT NULL ,
CANALID INT FOREIGN KEY REFERENCES CANAL(CANALID)
);

SELECT * FROM VIDEO 

CREATE TABLE AULA (
ID INT PRIMARY KEY,
NOME VARCHAR(200)
);
SELECT * FROM AULA


UPDATE AULA 
SET NOME  = 'ID'
WHERE ID = 3

DELETE FROM AULA 
WHERE  NOME = 'ID';

ALTER TABLE AULA 
ADD ATIVO BIT 

ALTER TABLE AULA 
ALTER COLUMN NOME  VARCHAR(300) NOT NULL

EXEC SP_RENAME 'AULA' , 'MATERIA'


